### ISSUE TITLE
Adding team auto-complete search in the `gameform`

### ISSUE THREAD

**Issue by itamadev** [chenPerach/Scouting_App_Off_Season#10]
I think it would be easier, faster, and more efficient for the scouter to be able to search with autocompletion for the team he is scouting.

A way to solve this is to either be able to search while keeping the scrolling list as is or removing it completely and only having the auto-complete search feature.

**Comment by chenPerach** [comment]
I thought about something like this. 
it is indeed a good feature to add to the backlog. 

don't expect this feature to be added soon, there are still lots of things to work on in the game form. 

- [ ] validity check the given match data. 
- [x] add the data to firebase data base. 
- [ ] add a match summery for showing all of the cycles submitted

*note: this all should really be added to a project or something*

**Comment by chenPerach** [comment]
added this feature to the app. [see](https://github.com/chenPerach/Scouting_App_Off_Season/commit/0f4b79034c9304e889b3226ae35bbc4f8812ec4f)
