### ISSUE TITLE
Adding a version

### ISSUE THREAD

**Issue by itamadev** [chenPerach/Scouting_App_Off_Season#11]
It's currently a hustle to know which version of the app is running or your machine, so a way to prompt it should make it easier to spot bug fixes or any use-cases requiring a version.

When a user opens the side drawer a `version` tab should be amongst the other tabs suggested to the user, preferably at the bottom as the footer of the drawer.

Alternatives should be having at as metadata of the app in the apps `options` or `settings` (should be set correctly anyways) currently set to 1.0.0 even though we are at version 0.0.3.

When fixing bugs or spotting them a version can be a life savior.

**Comment by chenPerach** [comment]
Thanks for the suggestion! this change was [added](https://github.com/chenPerach/Scouting_App_Off_Season/commit/bc60c540d5762e3f39bac070973a84c4050470a0)
