### ISSUE TITLE
App stuck on loading screen

### ISSUE THREAD

**Issue by cyyv** [chenPerach/Scouting_App_Off_Season#15]
**Describe the bug**
When I open the app it show the loading screen for a few seconds and than stop working.

Tried:
- deleting cache
- restarting the phone
- reinstalling the app
- returning to older versions
- switching to wifi
- force closing the app
- and more

**To Reproduce**
1. Open the app
2. Do nothing
3. See error

**Expected behavior**
Work.

**Smartphone (please complete the following information):**
 - Device: Redmi note 8 pro
 - OS: Xiaomi MIUI 10
- Android version: 10 qp1a
- API version: 29
 - wifi: strong
 - fully updated

![Screenshot_2021-06-23-12-29-18-742_com.android.settings.jpg](https://user-images.githubusercontent.com/68687942/123072944-a78bda80-d41e-11eb-8a82-576c641dad94.jpg)

**Comment by chenPerach** [comment]
[shit man](https://github.com/flutter/flutter/issues/73337)

**Comment by chenPerach** [comment]
I think i solved this issue in the new [2020isrde1](https://github.com/chenPerach/Scouting_App_Off_Season/tree/2020isde1) branch.

**Comment by coderof19clc7** [comment]
@chenPerach can you tell me how did you fix the issue?
