### ISSUE TITLE
Easier release tracking

### ISSUE THREAD

**Issue by itamadev** [chenPerach/Scouting_App_Off_Season#6]
As this project will probably be having a lot of pre-releases (mostly during alpha stages),
would be easier to access all of the releases in the releases page `GitHub` provides.

If that's not possible or doesn't seem like a good way to tackle this problem
I think documentation of how to obtain the latest release would suffice.

**Comment by chenPerach** [comment]
git hub has a release page? 

sheeeeeeeeeeee

**Comment by chenPerach** [comment]
releases probobly will be implemented after the upcoming [home Page](https://github.com/chenPerach/Scouting_App_Off_Season/tree/homePage) pull request.

right now there isn't any thing to "release"

**Comment by chenPerach** [comment]
added first release
