### ISSUE TITLE
Prompted with `not secure enough` password

### ISSUE THREAD

**Issue by itamadev** [chenPerach/Scouting_App_Off_Season#9]
When either registering or logging in if you write a password with special characters you are prompted with a 
`not secure enough`  message.

1. Go to the `register` or `login` pages
2. Type in a password with any of the following special characters: @, #, $, %, &
3. Either hit the `login` or `register` buttons 
4. See the prompted message `not secure enough`

**Expected behavior**
Either a clear statement of what characters shouldn't or aren't allowed to be used in the password field 
Or it should accept the password 

<img src="https://user-images.githubusercontent.com/37014285/122652564-27c4ee00-d148-11eb-84c5-bdd20373398d.jpeg" alt="bug image" width="320" height="600"/>

<img src="https://user-images.githubusercontent.com/37014285/122652566-2a274800-d148-11eb-8757-1b8ac4f9f912.jpeg" alt="bug image" width="320" height="600"/>

 - Device: Xaiomi A1
 - OS: Android 9
 - Patform: Released app
 - Version: 0.0.3

**Additional context**
The only characters tested are: `@, #, $, %, &`
could be more characters that this bug applies to

**Comment by chenPerach** [comment]
this issue was relevent at the time but accurding to issue #12 there is no way to enforce that any change that I will make to the validation process. 

friendship ended with firebase :((((
